# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## Base settings ##
# url:  # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: '/'
title: Frank's blog
description: > #this means to ignore newlines until "nav_lists:"
  Frank's Blog

nav_lists:
  - title: About
    url: /about.html

## GitHub repository (if the site is hosted by GitHub) ##
# repository: e.g. someone.github.io
# repository_tree: e.g. master

## Language & timezone ##
lang: en #the language of your site
timezone: New Zealand

## Author & social ##
author:
  name: Frank
  email:  wistreng@gmail.com
  facebook:  wistreng
  twitter:  wistreng
  github:  wistreng
  # googleplus:  #your Google+ username
  weibo:  wistreng
  douban:  wistreng
  linkedin:  Frank Zhang

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Google Analytics ##
# ga_tracking_id:  #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
